[action] optimize action view

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -348,19 +348,23 @@ jobs:
 
       - name: Bsp Scons Compile
         if: ${{ success() }}
-        shell: bash
         env:
           RTT_BSP: ${{ matrix.legs.RTT_BSP }}
           RTT_TOOL_CHAIN: ${{ matrix.legs.RTT_TOOL_CHAIN }}
           SRTT_BSP: ${{ join(matrix.legs.SUB_RTT_BSP, ',') }}
-          CPUS: $(cat /proc/cpuinfo | grep "processor" | sort | uniq | wc -l) 
         run: |
           source ~/.env/env.sh
+          failed=0
           count=0
-          echo $CPUS
           for bsp in $(echo $SRTT_BSP | tr ',' '\n'); do
             count=$((count+1))
-            echo "Compiling BSP: ==$count=== $bsp ===="
-            pushd bsp/$bsp && scons --pyconfig-silent && pkgs --update && popd
-            scons -C bsp/$bsp -j8
+            echo "::group::Compiling BSP: ==$count=== $bsp ===="
+            pushd bsp/$bsp && pkgs --update && popd
+            scons -C bsp/$bsp -j$(nproc) --debug=time | tee output.log || \
+            { total_time=$(grep "Total command execution time" output.log | awk '{print $5}'); \
+              failed=$((failed+1)) ; echo "::endgroup::" ; echo "::error::build $bsp failed" ; \
+              echo "- ❌ build $bsp failed in $total_time seconds " >> $GITHUB_STEP_SUMMARY ; } && \
+            { total_time=$(grep "Total command execution time" output.log | awk '{print $5}'); \
+              echo "- ✅ build $bsp success in $total_time seconds " >> $GITHUB_STEP_SUMMARY ; echo "::endgroup::" ; }
           done
+          exit $failed
