Update action.yml

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -371,7 +371,7 @@ jobs:
             count=$((count+1))
             echo "::group::Compiling BSP: ==$count=== $bsp ===="
             echo bsp/$bsp
-            ls bsp/$bsp/Kconfig && scons -C bsp/$bsp --pyconfig-silent 
+            {ls bsp/$bsp/Kconfig && scons -C bsp/$bsp --pyconfig-silent } || {echo "- ❌ menuconfig $bsp failed " >> $GITHUB_STEP_SUMMARY}
             pushd bsp/$bsp && pkgs --update && popd
             scons -C bsp/$bsp -j$(nproc) --debug=time | tee output.log || \
             { total_time=$(grep "Total command execution time" output.log | awk '{print $5}'); \
