Update cppcheck.yml

diff --git a/.github/workflows/cppcheck.yml b/.github/workflows/cppcheck.yml
--- a/.github/workflows/cppcheck.yml
+++ b/.github/workflows/cppcheck.yml
@@ -26,4 +26,8 @@ jobs:
           echo $changed_files
           if [ -n "$changed_files" ];then
               cppcheck --enable=warning,performance,portability --inline-suppr --error-exitcode=1 --force $changed_files
+              err=$?
+              if [ $err -ne 0 ]; then
+                  echo "Hello! we found a obvious fault, please fix the error then commit again"
+              fi
           fi
